const FETCH_USERS = 'FETCH_USERS'
const FETCH_POSTS ='FETCH_POSTS'
const FETCH_ALBUMS ='FETCH_ALBUMS'
const FETCH_TODOS ='FETCH_TODOS'
const FETCH_PHOTOS = 'FETCH_PHOTOS'
const FETCH_COMMENTS = 'FETCH_COMMENTS'

const CHANGE_ACTIVE_USER = 'CHANGE_ACTIVE_USER'
const CHANGE_IS_LOADING = 'CHANGE_IS_LOADING'
const CHANGE_IS_COMMENTS_LOADING = 'CHANGE_IS_COMMENTS_LOADING' 
const CHANGE_IS_PHOTOS_LOADING = 'CHANGE_IS_PHOTOS_LOADING'

export {FETCH_USERS, FETCH_POSTS, 
        FETCH_ALBUMS, FETCH_TODOS, 
        FETCH_PHOTOS, FETCH_COMMENTS,
        CHANGE_ACTIVE_USER, 
        CHANGE_IS_LOADING, CHANGE_IS_COMMENTS_LOADING, CHANGE_IS_PHOTOS_LOADING
        };