const FETCH_USERS = 'FETCH_USERS'
const CHANGE_ACTIVE_USER = 'CHANGE_ACTIVE_USER'

const FETCH_POSTS ='FETCH_POSTS'

const CHANGE_IS_LOADING = 'CHANGE_IS_LOADING'

export {FETCH_USERS, FETCH_POSTS, CHANGE_ACTIVE_USER, CHANGE_IS_LOADING};