const TODO_COMPLETE = 'TODO_COMPLETE';
const TODO_IMPORTANT = 'TODO_IMPORTANT';

const TODO_SELECTED = 'TODO_SELECTED'

const CHANGE_HEADER = 'CHANGE_HEADER'
const CHANGE_DATE = 'CHANGE_DATE'


export { TODO_COMPLETE, TODO_IMPORTANT, TODO_SELECTED, CHANGE_HEADER, CHANGE_DATE }